---
title: "About Me"
---

# Theresa Worden

insert picture of me here

## Professional

I am currently a senior at St. Olaf College, pursuing a double major in computer science and mathematics, and I will be graduating in December 2024. Throughout my time in school, I have developed an strong foundation in software development with an interest in full-stack development.

Over the past two summers, I have interned at Best Buy and Disney where I got to work on real world projects like tax integration software at Best Buy and employee web applications at Disney.

## Personal

I am from White Bear Lake, Minnesota (about 20-25 minutes outside of the twin cities). I was a very active child as I was a gymnast, soccer player, basketball player, and mixed martial arts student growing up. While gymnastics and mixed martial arts didn't stick around as long, I continued to play soccer and basketball into high school and played soccer into college for two years. After my soccer journey ended, a new journey started as a friend of mine introduced me to boxing. I have been boxing for a year and a half and have been loving it every second.

I have been playing the electric guitar since freshman year of high school. I love learning new songs and riffs and getting together with friends for a little jam session. Some of the bands that we like to play songs from are Blink-182, The Strokes, Green Day, The Smashing Pumpkins, and Muse.
