---
title: "The Saw Movies"
format:
  html:
    theme: lumen
    css: styles.css
    toc: true
editor: visual
---

# "I want to play a game."

The Saw movie franchise is my favorite movie franchise of all time. This is my ranking of each movie I have seen so far (Saw, Saw II, Saw III, Saw IV, Saw V, Saw VI, and Saw 3D).

------------------------------------------------------------------------

## 1. Saw

Easily the best movie in the franchise. A great introduction to the main villain, Jigsaw. It has my favorite plot twist of all time that quite literally left my jaw on the floor when I first saw it.

Favorite quote:

> "Yes, I'm sick, officer. Sick from the disease eating away at me inside. Sick of people who don't appreciate their blessings. Sick of those who scoff at the suffering of others. I'm sick of it all!"

------------------------------------------------------------------------

## 2. Saw II

Some fans say this is their favorite movie in the franchise. While I am not one of those people, I definitely understand where they are coming from. Saw II offers a different setting for those in the game, which becomes a blueprint for later movies in the series. It has a great balance between learning more about Jigsaw and showing the people in the traps as they progress throughout the house that is slowly killing them.

Favorite quote:

> "I want to play a game. The rules are simple. All you have to do is sit here and talk to me. Listen to me. If you do that long enough you will find your son in a safe and secure state. We haven't been properly introduced. My name's John."

------------------------------------------------------------------------

## 3. Saw VI

The reason Saw IV ranks this high is because of its commentary on the health insurance industry. The game that the main victim is put in feels ever more personal for Jigsaw as we learn more than ever about his back story. The plot twist at the end felt like satisfying closure after six movies in the franchise.

Favorite quote:

> "Don't talk to me about money. I have money."

------------------------------------------------------------------------

## 4. Saw III

The plot of this movie focuses less on figuring out "Who is Jigsaw?" and focuses more on emotion. The main victim has to face difficult decisions throughout the movie, which had me feeling sad for him at times. However, this is where I feel the quality of the movies starts to steadily decline.

Favorite quote:

> "My 20 second analysis without any medical equipment is that his brain is herniating."

------------------------------------------------------------------------

## 5. Saw IV 

Easily one of the more forgettable movies in the franchise. I had to look up what happened in this movie even though I have seen it multiple times. Quality is lacking compared to its predecessors. The plot twist leaves for much to be desired. There is not much to say other than the non-linear plot line with Saw III was the most interesting thing about this movie.

> "You know never to go through an unsecured door. Ever."

------------------------------------------------------------------------

## 7. Saw V 

**Test:** *The Trust Trap*

This movie is acceptable for what it is. It feels like a filler movie just to move the plot along and keep the franchise alive. Again, we see the decline of quality and questionable acting. The plot focuses more on a rivalry between Jigsaw's accomplice and an FBI agent, which diverts from the plot of previous movies. Not to say that this is a bad thing, just not what I really signed up for when it comes to a Saw movie.

> "Jigsaw doesn't make mistakes."

------------------------------------------------------------------------

## 8. Saw 3D

The most recent movie I have seen on the list and also my least favorite, so far. The plot and pacing left me discombobulated, and the uninspiring acting left me wanting more. Too many moments of cheesy 3D uses that did not the aesthetics of the movie.

Favorite quote:

> none

------------------------------------------------------------------------
